/* This file is automatically generated. Edits will be lost.*/
<<<<<<< HEAD
const int buildversion = 31;
=======
const int buildversion = 28;
>>>>>>> be0adb7f0c93c82dbae8ac5d268734077d23e603
const char buildconfig[] = "TLB_V1";
